export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_SCREENSHOTS_DIR="${XDG_SCREENSHOTS_DIR:-$XDG_DATA_HOME/pictures/screenshots}"
export ZDOTDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}"

export EDITOR="${EDITOR:-nvim}"
export VISUAL="${VISUAL:-$EDITOR}"
export MANPAGER="${MANPAGER:-bat --language=man --plain}"
export STARSHIP_CONFIG="${STARSHIP_CONFIG:-$XDG_CONFIG_HOME/starship.toml}"

path=("$HOME/.local/bin" $path)
typeset -U path PATH

[[ -r "$HOME/.zshenv.local" ]] && source "$HOME/.zshenv.local"
