#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

sort_order = ["tmux", "config", "zoxide"]

[tui]
show_icons = true
preview = true
preview_width = 60
preview_border = "line"

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "home"
path = "~"
disable_startup_command = true

[[wildcard]]
pattern = "~/**"
startup_command = "tmux rename-window shell"
windows = ["agent", "editor", "git"]

[[window]]
name = "agent"
startup_script = "cx"

[[window]]
name = "editor"
startup_script = "nvim"

[[window]]
name = "git"
startup_script = "if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then lazygit; else exit; fi"
